#!/usr/bin/env bash

LC_ALL=C

branch="$(git rev-parse --abbrev-ref HEAD)"

valid_regex="^(develop|master|release)\/[a-z0-9._-]+$"

if [[ ! $branch =~ $valid_regex ]]

then

	echo "Your commit was rejected due to branch name"
	
	echo "Please rename your branch with $valid_regex syntax"

	exit 1

fi

exit 0